export const  GUARDIAN_DEPORTATION = 'GUARDIAN_DEPORTATION'
export const  GUARDIAN_REJECT = 'GUARDIAN_REJECT'
export const  GUARDIAN_UPDATE_ALLOW_POSITION = 'GUARDIAN_UPDATE_ALLOW_POSITION'

export const VISITOR_GET_PERMIT = 'VISITOR_GET_PERMIT'
export const VISITOR_FORGET_ME = 'VISITOR_FORGET_ME'

export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'
export const LOGIN_RESET = 'LOGIN_RESET'
export const LOGIN_OUT = 'LOGIN_OUT'


export const GET_USER_ITEMS_SUCCESS = 'GET_USER_ITEMS_SUCCESS'
export const GET_USER_ITEMS_FAILURE = 'GET_USER_ITEMS_FAILURE'
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS'
export const CREATE_USER_FAILURE = 'CREATE_USER_FAILURE'
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS'
export const DELETE_USER_FAILURE = 'DELETE_USER_FAILURE'
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'
export const UPDATE_USER_FAILURE = 'UPDATE_USER_FAILURE'


