export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'
export const LOGIN_RESET = 'LOGIN_RESET'
export const LOGIN_OUT = 'LOGIN_OUT'

export const ASSISTANT_SHOW_MSG='ASSISTANT_SHOW_MSG'
export const ASSISTANT_REDIRECT='ASSISTANT_REDIRECT'
