export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'
export const LOGIN_RESET = 'LOGIN_RESET'
export const LOGIN_OUT = 'LOGIN_OUT'

export const ASSISTANT_SHOW_MSG='ASSISTANT_SHOW_MSG'
export const ASSISTANT_REDIRECT='ASSISTANT_REDIRECT'

export const GET_USER_ITEMS_SUCCESS = 'GET_USER_ITEMS_SUCCESS'
export const GET_USER_ITEMS_FAILURE = 'GET_USER_ITEMS_FAILURE'
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS'
export const CREATE_USER_FAILURE = 'CREATE_USER_FAILURE'
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS'
export const DELETE_USER_FAILURE = 'DELETE_USER_FAILURE'


